### ISSUE TITLE
demo?

### ISSUE THREAD

**Issue by davehorner** [hadibtf/PulsingCircle#1]
Do you have the code to the demo that could be included?  It is building but I'm not yet sure how to use it.

**Comment by hadibtf** [comment]
Just write this `PulsingCircle()` and done.
And keep in mind it's a Composable so it's only going to work inside a Composable function.

**Comment by hadibtf** [comment]
Just write this `PulsingCircle()` and done.
And keep in mind it's a Composable so it's only going to work inside a Composable function.
